//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_staff()
        {
            this.tbl_movement = new HashSet<tbl_movement>();
        }

        public byte stf_id { get; set; }

        [Required(ErrorMessage = "Personel Adý Zorunludur!")]
        [StringLength(30, ErrorMessage = "Ad 30 karakterden fazla olamaz")]
        public string stf_name { get; set; }

        [Required(ErrorMessage = "Personel Soyadý Zorunludur!")]
        [StringLength(30, ErrorMessage = "Soyad 30 karakterden fazla olamaz")]
        public string stf_surname { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_movement> tbl_movement { get; set; }
    }
}
