//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_author()
        {
            this.tbl_book = new HashSet<tbl_book>();
        }
    
        public int ath_id { get; set; }
        [Required(ErrorMessage ="Yazar Ýsmi Zorunludur!")]
        [StringLength(30,ErrorMessage ="Yazar Adý Maksimum 30 Karekter Olabilir!")]
        public string ath_name { get; set; }
        [Required(ErrorMessage = "Yazar Soyadý Zorunludur!")]
        [StringLength(30, ErrorMessage = "Yazar Soyadý Maksimum 30 Karekter Olabilir!")]
        public string ath_surname { get; set; }
        [StringLength(1000, ErrorMessage = "Detay Bölümü Maksimum 1000 Karekter Olabilir!")]
        public string ath_detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_book> tbl_book { get; set; }
    }
}
