//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_safe
    {
        public int sf_id { get; set; }
        public string sf_month { get; set; }
        public Nullable<decimal> sf_amount { get; set; }
    }
}
