//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_punishment
    {
        public int pnh_id { get; set; }
        public Nullable<int> pnh_mmb { get; set; }
        public Nullable<System.DateTime> pnh_begining { get; set; }
        public Nullable<System.DateTime> pnh_finish { get; set; }
        public Nullable<decimal> pnh_money { get; set; }
        public Nullable<int> pnh_mvm { get; set; }
    
        public virtual tbl_member tbl_member { get; set; }
        public virtual tbl_movement tbl_movement { get; set; }
    }
}
