//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_member()
        {
            this.tbl_movement = new HashSet<tbl_movement>();
            this.tbl_punishment = new HashSet<tbl_punishment>();
            this.tbl_message = new HashSet<tbl_message>();
            this.tbl_message1 = new HashSet<tbl_message>();
        }
    
        public int mmb_id { get; set; }
        [Required(ErrorMessage = "Ýsim Alaný Zorunludur!")]
        [StringLength(20, ErrorMessage = "Ýsim Alaný En Fazla 20 Karakter Alabilir!")]
        public string mmb_name { get; set; }
        [Required(ErrorMessage = "Soyisim Alaný Zorunludur!")]
        [StringLength(20, ErrorMessage = "Yayýnevi Alaný En Fazla 20 Karakter Alabilir!")]
        public string mmb_surname { get; set; }
        [Required(ErrorMessage = "E-Mail Alaný Zorunludur!")]
        [StringLength(50, ErrorMessage = "E-Mail Alaný En Fazla 50 Karakter Alabilir!")]
        public string mmb_email { get; set; }
        [Required(ErrorMessage = "Kullanýcý Adý Alaný Zorunludur!")]
        [StringLength(20, ErrorMessage = "Kullanýcý Adý Alaný En Fazla 20 Karakter Alabilir!")]
        public string mmb_username { get; set; }
        [Required(ErrorMessage = "Þifre Alaný Zorunludur!")]
        [StringLength(20, ErrorMessage = "Þifre Alaný En Fazla 20 Karakter Alabilir!")]
        public string mmb_password { get; set; }
        [StringLength(250, ErrorMessage = "Fotoðraf Alaný En Fazla 250 Karakter Alabilir!")]
        public string mmb_photo { get; set; }
        [Required(ErrorMessage = "Telefon Alaný Zorunludur!")]
        [StringLength(20, ErrorMessage = "Telefon Alaný En Fazla 20 Karakter Alabilir!")]
        public string mmb_tel { get; set; }
        [StringLength(100, ErrorMessage = "Okul Ýsmi Alaný En Fazla 100 Karakter Alabilir!")]
        public string mmb_school { get; set; }
        public Nullable<bool> mmb_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_movement> tbl_movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_punishment> tbl_punishment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_message> tbl_message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_message> tbl_message1 { get; set; }
    }
}
