//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public int msg_id { get; set; }
        public string msg_sender { get; set; }
        public string msg_recipient { get; set; }
        public string msg_subject { get; set; }
        public string msg_content { get; set; }
        public Nullable<System.DateTime> msg_date { get; set; }
    }
}
