//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_movement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_movement()
        {
            this.tbl_punishment = new HashSet<tbl_punishment>();
        }
    
        public int mvm_id { get; set; }
        public Nullable<int> mvm_bk { get; set; }
        public Nullable<int> mvm_mmb { get; set; }
        public Nullable<byte> mvm_stf { get; set; }
        public Nullable<System.DateTime> mvm_receipt_date { get; set; }
        public Nullable<System.DateTime> mvm_delivery_date { get; set; }
        public Nullable<bool> mvm_status { get; set; }
        public Nullable<System.DateTime> mvm_return_date { get; set; }
    
        public virtual tbl_book tbl_book { get; set; }
        public virtual tbl_member tbl_member { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_punishment> tbl_punishment { get; set; }
    }
}
